### ISSUE TITLE
Migration fails if i18n is added after spree_fancy was added to the app

### ISSUE THREAD

**Issue by fjahr** [spree-contrib/spree_fancy#66]
I added the spree_fancy gem before the i18n and I discovered this error. Moving the AddSlider... migration behind the i18n migrations fixed it for me. Still good to know :)

```
==  AddSliderTaxonsAndApplyThem: migrating ====================================
rake aborted!
An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "spree_taxonomy_translations" does not exist
LINE 5:                WHERE a.attrelid = '"spree_taxonomy_translati...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"spree_taxonomy_translations"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_no_cache'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:138:in `block in exec_query'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:425:in `block in log'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:420:in `log'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql_adapter.rb:915:in `column_definitions'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:174:in `columns'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/schema_cache.rb:114:in `block in prepare_default_proc'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/schema_cache.rb:56:in `yield'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/schema_cache.rb:56:in `columns'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/schema_cache.rb:118:in `block in prepare_default_proc'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/schema_cache.rb:67:in `yield'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/schema_cache.rb:67:in `columns_hash'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/association_scope.rb:25:in `column_for'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/association_scope.rb:37:in `bind'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/association_scope.rb:73:in `block in add_constraints'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/association_scope.rb:44:in `each'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/association_scope.rb:44:in `each_with_index'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/association_scope.rb:44:in `add_constraints'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/association_scope.rb:19:in `scope'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/association.rb:100:in `association_scope'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/association.rb:84:in `scope'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:382:in `scope'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/collection_proxy.rb:37:in `initialize'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/relation/delegation.rb:78:in `new'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/collection_association.rb:37:in `reader'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/associations/builder/association.rb:70:in `translations'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/globalize-4.0.0.alpha.2/lib/globalize/active_record/instance_methods.rb:125:in `translation_for'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/globalize-4.0.0.alpha.2/lib/globalize/active_record/adapter.rb:76:in `fetch_attribute'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/globalize-4.0.0.alpha.2/lib/globalize/active_record/adapter.rb:25:in `block in fetch'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/globalize-4.0.0.alpha.2/lib/globalize/active_record/adapter.rb:24:in `each'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/globalize-4.0.0.alpha.2/lib/globalize/active_record/adapter.rb:24:in `fetch'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/globalize-4.0.0.alpha.2/lib/globalize/active_record/instance_methods.rb:36:in `write_attribute'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/globalize-4.0.0.alpha.2/lib/globalize/active_record/class_methods.rb:142:in `block in translated_attr_accessor'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/attribute_assignment.rb:42:in `public_send'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/attribute_assignment.rb:29:in `block in assign_attributes'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/attribute_assignment.rb:23:in `each'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/attribute_assignment.rb:23:in `assign_attributes'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/globalize-4.0.0.alpha.2/lib/globalize/active_record/instance_methods.rb:19:in `block in assign_attributes'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/globalize-4.0.0.alpha.2/lib/globalize/active_record/instance_methods.rb:187:in `with_given_locale'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/globalize-4.0.0.alpha.2/lib/globalize/active_record/instance_methods.rb:19:in `assign_attributes'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/core.rb:192:in `initialize'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/inheritance.rb:27:in `new'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/inheritance.rb:27:in `new'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/persistence.rb:36:in `create'
/Users/FJ/Desktop/rails_projects/travelspree/db/migrate/20131112015835_add_slider_taxons_and_apply_them.spree_fancy.rb:4:in `up'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:574:in `exec_migration'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:555:in `block (2 levels) in migrate'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:554:in `block in migrate'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:553:in `migrate'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:709:in `migrate'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:959:in `block in execute_migration_in_transaction'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:1005:in `block in ddl_transaction'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/transactions.rb:209:in `transaction'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:1005:in `ddl_transaction'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:958:in `execute_migration_in_transaction'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:920:in `block in migrate'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:916:in `each'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:916:in `migrate'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:764:in `up'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/migration.rb:742:in `migrate'
/Users/FJ/.rvm/gems/ruby-2.0.0-p247/gems/activerecord-4.0.0/lib/active_record/railties/databases.rake:42:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by praWINK** [comment]
If you remove the 'spree_i18n' gem it will works...I hope it will works for others in future.
